---
abstract: ''
author:
  - 'SymKat I<<symkat@symkat.com>>'
build_requires:
  DBD::SQLite: 0
  Test::MockObject: 1.09
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Schema-Config
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0.08100
  perl: 5.005
version: 0.001002
