---
abstract: 'Manage connection credentials for DBIx::Class::Schema in a file.'
author:
  - 'SymKat I<<symkat@symkat.com>>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::MockObject: 1.09
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Schema-Config
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0.08100
  perl: 5.005
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 0.001000
